### ISSUE TITLE
Replace numpy power by TF pow

### ISSUE THREAD

**Issue by rubenverhack** [amirgholami/adahessian#15]
https://github.com/amirgholami/adahessian/blob/bacccecc7a078c3e9e72aa55b17d8e46d21dc9c9/adahessian_tf/adahessian.py#L384

Do not use numpy functions within a tf.function decorator. Use tensorflow implementation if possible.
~~~

        denom = tf.math.pow(math_ops.sqrt(v / bias_correct2), self.hessian_power) + coefficients['epsilon']
~~~

**Comment by amirgholami** [comment]
Many thanks for the suggestion. This is now fixed.
