### ISSUE TITLE
Error using adahessian in PyTorch

### ISSUE THREAD

**Issue by johnhalloran321** [amirgholami/adahessian#17]
Hi,

I've tried using adahessian as a drop-in replacement for adadelta in the PyTorch mnist example (with loss.backward(create_graph=True)), but this produces the error:

NameError: name 'gradsH' is not defined

This variable looks to be underfined in instruction/adahessian.py, is there something I'm missing?

Thanks!

**Comment by amirgholami** [comment]
Hi,

Thanks for pointing this out. We have just fixed that. Please let us know if there was any other problems.

However, if you are using this for CV tasks with a convolutional NN then we suggest directly using the code that we have provided in image classification directory:

https://github.com/amirgholami/adahessian/tree/master/image_classification

and specifically:
https://github.com/amirgholami/adahessian/blob/master/image_classification/optim_adahessian.py


Also as a side note pytorch-optimizer library already has the adahessian integrated and you can use adahessian as a drop-in replacement there:
https://github.com/jettify/pytorch-optimizer

**Comment by johnhalloran321** [comment]
Hi,

Using both image_classification/optim_adahessian.py and the pytorch-optimizer package worked, thanks for the quick response!

Using instruction/adahessian.py produces the error: "NameError: name 'hut_trace' is not defined"

Is there any difference between the instruction/adahessian.py and image_classification/optim_adahessian.py implementations?

**Comment by amirgholami** [comment]
Thanks for point this out. Zhewei's latest commit should resolve that issue.
