### ISSUE TITLE
Is Hutch++ applicable to improve AdaHessian?

### ISSUE THREAD

**Issue by sjscotti** [amirgholami/adahessian#23]
Hi
I recently came across this paper on an improved accuracy Hutchinson method, but I am not well versed enough in the discipline to know if it can be used with AdaHessian.  Do you think it can be used to improve AdaHessian?

https://arxiv.org/pdf/2010.09649.pdf

**Comment by amirgholami** [comment]
Thank you for sharing the paper. Yes it is possible to use this algorithm in a matrix free manner. However, in AdaHessian we only apply one Hutchinson iteration per optimization step. From a quick look, this algorithm requires multiple random samples.

However, this algorithm could be added to PyHessian library, and I expect that it would give better results for large number of Hutchinson iterations.
