### ISSUE TITLE
Alternative to Rademacher distribution

### ISSUE THREAD

**Issue by nestordemeure** [amirgholami/adahessian#7]
Hello,

First, congratulation for developing AdaHessian, it is a great idea!

Second, have you experimented with alternatives to the Rademacher distribution?
A uniform or gaussian distribution should also work and, depending on the characteristics of the Hessian, might be a better default.

Have a good day,
Nestor

**Comment by amirgholami** [comment]
Hi Nestor, 

Yes you can use Gaussian random numbers as well. However, Rademacher random numbers have better convergence. For details please see the following paper:


Ubaru S, Chen J, Saad Y. Fast Estimation of tr(f(A)) via Stochastic Lanczos Quadrature. SIAM Journal on Matrix Analysis and Applications. 2017;38(4):1075-99.


Best,
-Amir
