### ISSUE TITLE
too many abs ?

### ISSUE THREAD

**Issue by nestordemeure** [amirgholami/adahessian#8]
While looking at your averaging code (line 89 to 144 of [this file](https://github.com/amirgholami/adahessian/blob/master/instruction/adahessian.py)) I noticed that you compute `abs(sum(abs(hv * vi)))`.
As far as I understand it, the outer absolute value is not needed as you are already doind a sum of positive terms.

Also, note that if you are using a Rademarcher distribution, you can drop the `vi` term from `torch.sum(torch.abs(hv * vi))` as `abs(vi) == 1` (but keeping it in place might make the algorithm easier to read as it keeps the code close to the math).

**Comment by amirgholami** [comment]
Hi Nestor,

We are computing the sum of squares of the diagonal elements. Some of these abs functions can be removed but we included them so that the algorithm is clear and easier to read.

Best,
-Amir
