### ISSUE TITLE
AdaHessian tensorflow implementation

### ISSUE THREAD

**Issue by iron9light** [amirgholami/adahessian#9]
Hi,
First of all, really nice work!
I do wanna try your 2nd order optimizer now.
But I only know tensorflow and all my existing models are implimentad with tensorflow.
Could you provide a tensorflow version?

It seems you only need to implement the method below:
`python
def get_trace(grad, var)
`

**Comment by yaozhewei** [comment]
We have added the TensorFlow implementation. Please let us know if you cannot use it on your end.

**Comment by Cyberface** [comment]
I second this, this is really exciting work! I am itching to try this in my tensorflow models as well but I don't use a custom training loop but instead just pass in the optimizer at the compile step. Is it possible to use AdaHessian in a similar way? If so can you provide an example?

Thanks!
